language: node_js
cache:
  directories:
  - node_modules
  - bower_components
node_js:
- '0.12'
before_script:
- npm install -g bower
- bower install
script:
- npm test
after_script:
- webpack --production
after_success:
- scripts/push-to-backend.sh
env:
  global:
  - GH_REF: github.com/lovedota/angular-regex-frontend
  - secure: ox1fKAF79acFGBYw1QzwIlc5mbENiup40GtefpyqqxkIrFlXxr/3qSJthYa3/mVdXKfvQcmiFLhbxBIAUMOl0j4bL4zKcMd9WBTyoncbjMS04IYdDVgw5Al5EFlK3NvSiJouy14x5c3ZSJtwcOisGT4VuDaYrrvaoE48AZchoEilhTLI95uXlCuHwfEWr5t2VUZJRt862EcjrjJrr1Dn+K5sxgpqNyaRI0UHiT3jAU05TCVGFLTDvo5MLbKsYC20/encqMGiin8p4WjWSydGm06hTJ15YEVRe9XaPXGjDpg81167xH23psSlSGZJKKSMaz0T8ZsR92KeQjwTVw96GX/vULXB1xfrMlqzOYInHV4iN2o4dwhFhrcaGSAkdRciSr94iY35n13Fx+yck+L03hXjVIOAL5oC8juB4cmIX78IV9iRNIG7NdiLMY8BqwawtzKQ8jf3BmkrgmWbuxbQbryTcngAmW9XIoHD69odjXoBLSHAX10kHDS+428m/wlBjN8op//4ul7crgCkLfD9dXHX1o3EFqvQfySncTTvaeUypAUYrH4kwuB1qinEvXPmav5vIsN0VcW9rfRw3zumVDsQ3DUpqmU8Z3Y1MZbRVo12dOt0NobWioDjg/yQqEtFFj+1DVRHisVDddmYHQ4cPjfdtwLC/WH71Z8ey4Z5JX0=
