language: node_js
cache:
  directories:
  - node_modules
  - bower_components
node_js:
  - "0.12"
before_script:
  - bower install
script:
 - npm test
after_script:
  - webpack
after_success:
- scripts/push-to-ghpages.sh