language: node_js
cache:
  directories:
  - node_modules
  - bower_components
node_js:
- '0.12'
before_script:
- npm install -g bower
- bower install
script:
- npm test
after_script:
- webpack --production
after_success:
- scripts/push-to-backend.sh
env:
  global:
  - GH_REF: github.com/lovedota/angular-regex-frontend
  - secure: b8QkVNEND0/cUmKo4oyy/DNNl1SNxW5hXcrTQZm9yQCBBUb+WD8CSucJZhzOaxCcqeLWLeKaTPIf+qgPZHqcJvikO0Q1CKNeIo1ilRx0AjBUM8yT1RPzoZgWlx/etf1Glj/1xxdxlzUrHD+1rxe+zphhSONjWwaLHu83HY5f4aZ8rbHjbX5AoDBnVqD8blnGmibNTgcZf0lUOzcDwZ9NM68InMrI10UHN95+S7mmtDrEPpvYr4C4693R3RgePN01x+JQUUhEacchJy2Gx6jergxiZdQ/eRpdgD7A/E+QpvnTfNglc9Of5NblN8Ga1E13l3O3o8m+qYFaDfU8Jki4FOM5DSJkxw3a8gXwi+CVf3RpXNzK8E2DhWkV620hQ/Dmh3DMqldabcOy608CKd/wG5S/j0Yg7vSI+Zfiy4oRPTmOlDIXqxK+CfzX5eklnWWwWUkkUPkGq6bw2xu4HvMlXL5xZEF6Lb2VqfdsKTB+1ffciCg+3ly5I46r3Qx/5GPtFarYhDp6B5/c6ZEQansIVH2WJFgDTtQMIArVYRfWPCBY+1zZ/7zCHmRu3ZqycMxI+B3+FQdRqT4OL6pkUgrzqSFtQG0vxK5UOtfGJWEzNn5VLPTU6CK/T6sdBEt0a/4kcDr/o/yP9CBwZbUAw4sjeTRuqGmnzJCIY6/Zjfp7ipw=
